In [ ]:
# converting the excel file to csv file
import pandas as pd

In [4]:
supply_xl=pd.read_excel("supply.xlsx")
supply_xl.head()

,Parameter,STATE,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,...,2025-08,2025-09,2025-10,2025-11,2025-12,2026-01,2026-02,2026-03,2026-04,2026-05
0,Electricity Supplied(in MU),Tamil Nadu,8112,8165,8257,8901,8531,8373,8324,6508,...,11271,10972,10087,10076,10150,10067,10125,12233,12922,12400

In [6]:
df_long=supply_xl.melt(
    id_vars=["Parameter","STATE"],
    var_name="Date",
    value_name="Electricity_Supply"
)

In [8]:
df_long=df_long[["Date","Electricity_Supply"]]

In [22]:
df_long["Date"]=pd.to_datetime(df_long["Date"])

In [23]:
df_long = df_long.sort_values("Date").reset_index(drop=True)

In [24]:
df_long.head()

        Date  Electricity_Supply
0 2015-04-01              8112.0
1 2015-05-01              8165.0
2 2015-06-01              8257.0
3 2015-07-01              8901.0
4 2015-08-01              8531.0

In [25]:
df_long.to_csv("supply.csv",index=False)

In [26]:
import pandas as pd
from functools import reduce

# Read all CSV files
electricity = pd.read_csv("Electricity Requirement.csv")
humidity = pd.read_csv("Humidity Datasets.csv")
rainfall = pd.read_csv("Rainfall datasets.csv")
supply=pd.read_csv("supply.csv")
solar = pd.read_csv("solar_irradiance.csv")
temperature = pd.read_csv("Temperature Dataset.csv")

# Convert Date column to datetime
datasets = [
    electricity,
    humidity,
    rainfall,
    supply,
    solar,
    temperature
]

for df in datasets:
    df["Date"] = pd.to_datetime(df["Date"])

# Merge all datasets on Date
merged_df = reduce(
    lambda left, right: pd.merge(
        left,
        right,
        on="Date",
        how="inner"
    ),
    datasets
)

# Sort by Date
merged_df = merged_df.sort_values("Date").reset_index(drop=True)

# Save merged dataset
merged_df.to_csv("Final_Merged_Dataset.csv", index=False)
merged_df.head(15)

,Date,Electricity_Requirement,Humidity,Rainfall,Electricity_Supply,Solar_Irradiance,Temperature
0,2016-01-01,8151.0,78.24,2.164286,8150.0,162.750000,23.84
1,2017-01-01,8286.6,66.75,41.844286,8287.4,151.660000,25.03
2,2018-01-01,8620.9,72.98,7.354857,8613.9,162.380000,24.18
3,2019-01-01,8681.0,67.84,0.786286,8684.0,136.780000,24.33
4,2020-01-01,8544.0,76.99,9.249714,8547.0,158.500000,24.82
5,2021-01-01,7886.0,85.87,237.878000,7887.0,139.220000,23.96
6,2022-01-01,8873.0,81.80,40.069429,8873.0,157.910000,24.49
7,2023-01-01,9230.0,74.83,12.746857,9203.0,152.220000,23.66
8,2024-01-01,9658.0,80.30,37.970286,9630.0,140.880000,24.62
9,2025-01-01,9795.0,80.46,31.285429,9717.0,268.909644,23.86

In [28]:
# Check the Date column format in all datasets

datasets = {
    "Electricity": electricity,
    "Humidity": humidity,
    "Rainfall": rainfall,
    "Supply": supply,
    "Solar": solar,
    "Temperature": temperature
}

for name, df in datasets.items():
    print("=" * 60)
    print(f"{name} Dataset")

    # Check if Date column exists
    if "Date" in df.columns:
        print("\nDate Data Type:")
        print(df["Date"].dtype)

        print("\nFirst 10 Dates:")
        print(df["Date"].head(10).tolist())

        print("\nLast 10 Dates:")
        print(df["Date"].tail(10).tolist())

        print("\nTotal Rows:", len(df))

    else:
        print("No 'Date' column found!")

============================================================
Electricity Dataset

Date Data Type:
datetime64[ns]

First 10 Dates:
[Timestamp('2015-04-01 00:00:00'), Timestamp('2015-05-01 00:00:00'), Timestamp('2015-06-01 00:00:00'), Timestamp('2015-07-01 00:00:00'), Timestamp('2015-08-01 00:00:00'), Timestamp('2015-09-01 00:00:00'), Timestamp('2015-10-01 00:00:00'), Timestamp('2015-11-01 00:00:00'), Timestamp('2015-12-01 00:00:00'), Timestamp('2016-01-01 00:00:00')]

Last 10 Dates:
[Timestamp('2025-08-01 00:00:00'), Timestamp('2025-09-01 00:00:00'), Timestamp('2025-10-01 00:00:00'), Timestamp('2025-11-01 00:00:00'), Timestamp('2025-12-01 00:00:00'), Timestamp('2026-01-01 00:00:00'), Timestamp('2026-02-01 00:00:00'), Timestamp('2026-03-01 00:00:00'), Timestamp('2026-04-01 00:00:00'), Timestamp('2026-05-01 00:00:00')]

Total Rows: 134
============================================================
Humidity Dataset

Date Data Type:
datetime64[ns]

First 10 Dates:
[Timestamp('2015-01-01 00:00:00'), Timestamp('2015-01-02 00:00:00'), Timestamp('2015-01-03 00:00:00'), Timestamp('2015-01-04 00:00:00'), Timestamp('2015-01-05 00:00:00'), Timestamp('2015-01-06 00:00:00'), Timestamp('2015-01-07 00:00:00'), Timestamp('2015-01-08 00:00:00'), Timestamp('2015-01-09 00:00:00'), Timestamp('2015-01-10 00:00:00')]

Last 10 Dates:
[Timestamp('2025-01-03 00:00:00'), Timestamp('2025-01-04 00:00:00'), Timestamp('2025-01-05 00:00:00'), Timestamp('2025-01-06 00:00:00'), Timestamp('2025-01-07 00:00:00'), Timestamp('2025-01-08 00:00:00'), Timestamp('2025-01-09 00:00:00'), Timestamp('2025-01-10 00:00:00'), Timestamp('2025-01-11 00:00:00'), Timestamp('2025-01-12 00:00:00')]

Total Rows: 132
============================================================
Rainfall Dataset

Date Data Type:
datetime64[ns]

First 10 Dates:
[Timestamp('2015-01-01 00:00:00'), Timestamp('2015-01-02 00:00:00'), Timestamp('2015-01-03 00:00:00'), Timestamp('2015-01-04 00:00:00'), Timestamp('2015-01-05 00:00:00'), Timestamp('2015-01-06 00:00:00'), Timestamp('2015-01-07 00:00:00'), Timestamp('2015-01-08 00:00:00'), Timestamp('2015-01-09 00:00:00'), Timestamp('2015-01-10 00:00:00')]

Last 10 Dates:
[Timestamp('2025-01-03 00:00:00'), Timestamp('2025-01-04 00:00:00'), Timestamp('2025-01-05 00:00:00'), Timestamp('2025-01-06 00:00:00'), Timestamp('2025-01-07 00:00:00'), Timestamp('2025-01-08 00:00:00'), Timestamp('2025-01-09 00:00:00'), Timestamp('2025-01-10 00:00:00'), Timestamp('2025-01-11 00:00:00'), Timestamp('2025-01-12 00:00:00')]

Total Rows: 132
============================================================
Supply Dataset

Date Data Type:
datetime64[ns]

First 10 Dates:
[Timestamp('2015-04-01 00:00:00'), Timestamp('2015-05-01 00:00:00'), Timestamp('2015-06-01 00:00:00'), Timestamp('2015-07-01 00:00:00'), Timestamp('2015-08-01 00:00:00'), Timestamp('2015-09-01 00:00:00'), Timestamp('2015-10-01 00:00:00'), Timestamp('2015-11-01 00:00:00'), Timestamp('2015-12-01 00:00:00'), Timestamp('2016-01-01 00:00:00')]

Last 10 Dates:
[Timestamp('2025-08-01 00:00:00'), Timestamp('2025-09-01 00:00:00'), Timestamp('2025-10-01 00:00:00'), Timestamp('2025-11-01 00:00:00'), Timestamp('2025-12-01 00:00:00'), Timestamp('2026-01-01 00:00:00'), Timestamp('2026-02-01 00:00:00'), Timestamp('2026-03-01 00:00:00'), Timestamp('2026-04-01 00:00:00'), Timestamp('2026-05-01 00:00:00')]

Total Rows: 134
============================================================
Solar Dataset

Date Data Type:
datetime64[ns]

First 10 Dates:
[Timestamp('2015-01-01 00:00:00'), Timestamp('2015-01-02 00:00:00'), Timestamp('2015-01-03 00:00:00'), Timestamp('2015-01-04 00:00:00'), Timestamp('2015-01-05 00:00:00'), Timestamp('2015-01-06 00:00:00'), Timestamp('2015-01-07 00:00:00'), Timestamp('2015-01-08 00:00:00'), Timestamp('2015-01-09 00:00:00'), Timestamp('2015-01-10 00:00:00')]

Last 10 Dates:
[Timestamp('2025-01-03 00:00:00'), Timestamp('2025-01-04 00:00:00'), Timestamp('2025-01-05 00:00:00'), Timestamp('2025-01-06 00:00:00'), Timestamp('2025-01-07 00:00:00'), Timestamp('2025-01-08 00:00:00'), Timestamp('2025-01-09 00:00:00'), Timestamp('2025-01-10 00:00:00'), Timestamp('2025-01-11 00:00:00'), Timestamp('2025-01-12 00:00:00')]

Total Rows: 132
============================================================
Temperature Dataset

Date Data Type:
datetime64[ns]

First 10 Dates:
[Timestamp('2015-01-01 00:00:00'), Timestamp('2015-01-02 00:00:00'), Timestamp('2015-01-03 00:00:00'), Timestamp('2015-01-04 00:00:00'), Timestamp('2015-01-05 00:00:00'), Timestamp('2015-01-06 00:00:00'), Timestamp('2015-01-07 00:00:00'), Timestamp('2015-01-08 00:00:00'), Timestamp('2015-01-09 00:00:00'), Timestamp('2015-01-10 00:00:00')]

Last 10 Dates:
[Timestamp('2025-01-03 00:00:00'), Timestamp('2025-01-04 00:00:00'), Timestamp('2025-01-05 00:00:00'), Timestamp('2025-01-06 00:00:00'), Timestamp('2025-01-07 00:00:00'), Timestamp('2025-01-08 00:00:00'), Timestamp('2025-01-09 00:00:00'), Timestamp('2025-01-10 00:00:00'), Timestamp('2025-01-11 00:00:00'), Timestamp('2025-01-12 00:00:00')]

Total Rows: 132

In [31]:
# Fix the wrongly encoded monthly dates

humidity["Date"] = pd.to_datetime({
    "year": humidity["Date"].dt.year,
    "month": humidity["Date"].dt.day,
    "day": 1
})

rainfall["Date"] = pd.to_datetime({
    "year": rainfall["Date"].dt.year,
    "month": rainfall["Date"].dt.day,
    "day": 1
})

solar["Date"] = pd.to_datetime({
    "year": solar["Date"].dt.year,
    "month": solar["Date"].dt.day,
    "day": 1
})

temperature["Date"] = pd.to_datetime({
    "year": temperature["Date"].dt.year,
    "month": temperature["Date"].dt.day,
    "day": 1
})

In [32]:
print(humidity.head(15))

         Date  Humidity
0  2015-01-01     74.53
1  2015-02-01     64.86
2  2015-03-01     61.84
3  2015-04-01     70.07
4  2015-05-01     77.22
5  2015-06-01     77.55
6  2015-07-01     73.18
7  2015-08-01     72.58
8  2015-09-01     75.12
9  2015-10-01     78.86
10 2015-11-01     87.29
11 2015-12-01     86.52
12 2016-01-01     78.24
13 2016-02-01     68.74
14 2016-03-01     60.87

In [33]:
datasets = [
    electricity,
    humidity,
    rainfall,
    supply,
    solar,
    temperature
]

for df in datasets:
    df["Date"] = pd.to_datetime(df["Date"])

# Merge all datasets on Date
merged_df = reduce(
    lambda left, right: pd.merge(
        left,
        right,
        on="Date",
        how="inner"
    ),
    datasets
)

# Sort by Date
merged_df = merged_df.sort_values("Date").reset_index(drop=True)

# Save merged dataset
merged_df.to_csv("Final_Merged_Dataset.csv", index=False)
merged_df.head(15)

,Date,Electricity_Requirement,Humidity,Rainfall,Electricity_Supply,Solar_Irradiance,Temperature
0,2015-04-01,8361.0,70.07,130.566857,8112.0,166.53,28.57
1,2015-05-01,8381.0,77.22,160.792286,8165.0,155.03,27.95
2,2015-06-01,8302.0,77.55,98.240286,8257.0,160.31,27.31
3,2015-07-01,8953.0,73.18,37.804286,8901.0,166.41,27.68
4,2015-08-01,8535.0,72.58,63.944286,8531.0,167.12,27.85
5,2015-09-01,8498.0,75.12,119.769714,8373.0,157.25,27.50
6,2015-10-01,8330.0,78.86,153.807429,8324.0,143.69,26.60
7,2015-11-01,6511.0,87.29,316.494857,6508.0,92.62,25.04
8,2015-12-01,7181.0,86.52,141.629143,7174.0,114.06,24.37
9,2016-01-01,8151.0,78.24,2.164286,8150.0,162.75,23.84
10,2016-02-01,8386.0,68.74,9.617714,8387.0,174.41,26.39
11,2016-03-01,9688.0,60.87,15.343714,9686.0,204.47,29.36
12,2016-04-01,9847.4,61.62,22.442000,9842.3,191.19,31.11
13,2016-05-01,9292.9,70.07,136.451714,9294.1,166.19,29.45
14,2016-06-01,8744.5,74.05,83.717714,8742.8,147.03,27.64

In [35]:
merged_df.shape

(129, 7)

In [9]:
print(electricity.shape)
print(humidity.shape)
print(rainfall.shape)
print(solar.shape)
print(supply.shape)
print(temperature.shape)

(134, 2)
(132, 2)
(132, 2)
(132, 2)
(129, 10)
(132, 2)

In [10]:
print(electricity["Date"].dtype)
print(humidity["Date"].dtype)
print(rainfall["Date"].dtype)
print(solar["Date"].dtype)
print(supply["Date"].dtype)
print(temperature["Date"].dtype)

datetime64[ns]
datetime64[ns]
datetime64[ns]
datetime64[ns]
datetime64[ns]
datetime64[ns]

In [11]:
print(electricity["Date"].nunique())
print(humidity["Date"].nunique())
print(rainfall["Date"].nunique())
print(solar["Date"].nunique())
print(supply["Date"].nunique())
print(temperature["Date"].nunique())

134
132
132
132
129
132

In [12]:
print("Electricity")
print(electricity["Date"].sort_values().head(15))
print(electricity["Date"].sort_values().tail(15))

print("\nSupply")
print(supply["Date"].sort_values().head(15))
print(supply["Date"].sort_values().tail(15))

Electricity
0    2015-04-01
1    2015-05-01
2    2015-06-01
3    2015-07-01
4    2015-08-01
5    2015-09-01
6    2015-10-01
7    2015-11-01
8    2015-12-01
9    2016-01-01
10   2016-02-01
11   2016-03-01
12   2016-04-01
13   2016-05-01
14   2016-06-01
Name: Date, dtype: datetime64[ns]
119   2025-03-01
120   2025-04-01
121   2025-05-01
122   2025-06-01
123   2025-07-01
124   2025-08-01
125   2025-09-01
126   2025-10-01
127   2025-11-01
128   2025-12-01
129   2026-01-01
130   2026-02-01
131   2026-03-01
132   2026-04-01
133   2026-05-01
Name: Date, dtype: datetime64[ns]

Supply
0    2015-04-01
1    2015-05-01
2    2015-06-01
3    2015-07-01
4    2015-08-01
5    2015-09-01
6    2015-10-01
7    2015-11-01
8    2015-12-01
9    2016-01-01
10   2016-02-01
11   2016-03-01
12   2016-04-01
13   2016-05-01
14   2016-06-01
Name: Date, dtype: datetime64[ns]
114   2024-10-01
115   2024-11-01
116   2024-12-01
117   2025-01-01
118   2025-02-01
119   2025-03-01
120   2025-04-01
121   2025-05-01
122   2025-06-01
123   2025-07-01
124   2025-08-01
125   2025-09-01
126   2025-10-01
127   2025-11-01
128   2025-12-01
Name: Date, dtype: datetime64[ns]

In [13]:
print(supply["Date"].head(20))
print(supply["Date"].tail(20))

0    2015-04-01
1    2015-05-01
2    2015-06-01
3    2015-07-01
4    2015-08-01
5    2015-09-01
6    2015-10-01
7    2015-11-01
8    2015-12-01
9    2016-01-01
10   2016-02-01
11   2016-03-01
12   2016-04-01
13   2016-05-01
14   2016-06-01
15   2016-07-01
16   2016-08-01
17   2016-09-01
18   2016-10-01
19   2016-11-01
Name: Date, dtype: datetime64[ns]
109   2024-05-01
110   2024-06-01
111   2024-07-01
112   2024-08-01
113   2024-09-01
114   2024-10-01
115   2024-11-01
116   2024-12-01
117   2025-01-01
118   2025-02-01
119   2025-03-01
120   2025-04-01
121   2025-05-01
122   2025-06-01
123   2025-07-01
124   2025-08-01
125   2025-09-01
126   2025-10-01
127   2025-11-01
128   2025-12-01
Name: Date, dtype: datetime64[ns]

In [14]:
print(solar["Date"].head(20))
print(solar["Date"].tail(20))

0    2015-01-01
1    2015-01-02
2    2015-01-03
3    2015-01-04
4    2015-01-05
5    2015-01-06
6    2015-01-07
7    2015-01-08
8    2015-01-09
9    2015-01-10
10   2015-01-11
11   2015-01-12
12   2016-01-01
13   2016-01-02
14   2016-01-03
15   2016-01-04
16   2016-01-05
17   2016-01-06
18   2016-01-07
19   2016-01-08
Name: Date, dtype: datetime64[ns]
112   2024-01-05
113   2024-01-06
114   2024-01-07
115   2024-01-08
116   2024-01-09
117   2024-01-10
118   2024-01-11
119   2024-01-12
120   2025-01-01
121   2025-01-02
122   2025-01-03
123   2025-01-04
124   2025-01-05
125   2025-01-06
126   2025-01-07
127   2025-01-08
128   2025-01-09
129   2025-01-10
130   2025-01-11
131   2025-01-12
Name: Date, dtype: datetime64[ns]

In [15]:
print(electricity.columns)
print(supply.columns)

Index(['Date', 'Electricity_Requirement'], dtype='object')
Index(['Date', 'Coal - Generation (in MU)', 'Oil & Gas - Generation (in MU)',
       'Nuclear - Generation (in MU)', 'Hydro - Generation (in MU)',
       'Solar - Generation (in MU)', 'Wind - Generation (in MU)',
       'Small-Hydro - Generation (in MU)', 'Bio Power - Generation (in MU)',
       'Total'],
      dtype='object')