In [ ]:
import pandas as pd
import numpy as np

In [13]:
df=pd.read_excel("../Datasets/Peak_Demand.xlsx")
df.head()

,Parameter,STATE,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,...,2025-08,2025-09,2025-10,2025-11,2025-12,2026-01,2026-02,2026-03,2026-04,2026-05
0,Peak Demand(in MW),Tamil Nadu,12969.0,13295.0,13278.0,14615.0,13757.0,13833.0,13307.0,12481.0,...,19275.0,18682.0,17887.0,18020.0,17842.0,17610.0,19326.0,20211.0,21326.0,19787.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Copyright © 2026, NITI Aayog | India's Climate...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://iced.niti.gov.in,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,The information on this platform is mainly tak...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df=df.iloc[:1]
df.head()

,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,...,2025-08,2025-09,2025-10,2025-11,2025-12,2026-01,2026-02,2026-03,2026-04,2026-05
0,12969.0,13295.0,13278.0,14615.0,13757.0,13833.0,13307.0,12481.0,12684.0,13576.0,...,19275.0,18682.0,17887.0,18020.0,17842.0,17610.0,19326.0,20211.0,21326.0,19787.0

In [ ]:
df.head()

,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,...,2025-08,2025-09,2025-10,2025-11,2025-12,2026-01,2026-02,2026-03,2026-04,2026-05
0,12969.0,13295.0,13278.0,14615.0,13757.0,13833.0,13307.0,12481.0,12684.0,13576.0,...,19275.0,18682.0,17887.0,18020.0,17842.0,17610.0,19326.0,20211.0,21326.0,19787.0

In [22]:
df = df.melt(
    var_name="Date",
    value_name="Peak_Demand"
)

In [23]:
df.head()

      Date  Peak_Demand
0  2015-04      12969.0
1  2015-05      13295.0
2  2015-06      13278.0
3  2015-07      14615.0
4  2015-08      13757.0

In [24]:
df["Date"] = pd.to_datetime(df["Date"])

In [27]:
df.head()

        Date  Peak_Demand
0 2015-04-01      12969.0
1 2015-05-01      13295.0
2 2015-06-01      13278.0
3 2015-07-01      14615.0
4 2015-08-01      13757.0

In [29]:
df.duplicated().sum()

0

In [30]:
print(df["Date"].min())
print(df["Date"].max())

2015-04-01 00:00:00
2026-05-01 00:00:00

In [32]:
df["Peak_Demand"]=df["Peak_Demand"].astype(int)

In [34]:
df.to_excel(
    "../Datasets/Peak_Demand.xlsx",
    index=False
)