# Rainfall Data's

In [42]:
import pandas as pd
import numpy as np

In [43]:
df1=pd.read_csv("../Datasets/Rainfall datasets.csv")
df1["Date"].min()

'2015-01-01'

In [44]:
df1["Date"].max()

'2025-12-01'

# Temperature Data's

In [45]:
df1=pd.read_csv("../Datasets/Temperature Dataset.csv")
df1["Date"].min()

'2015-01-01'

In [46]:
df1["Date"].max()

'2025-12-01'

# Humidity Data's

In [47]:
df1=pd.read_csv("../Datasets/Humidity Datasets.csv")
df1["Date"].min()

'2015-01-01'

In [48]:
df1["Date"].max()

'2025-12-01'

# solar irradinace data's

In [49]:
df1=pd.read_csv("../Datasets/solar_irradiance.csv")
df1["Date"].min()

'2015-01-01'

In [50]:
df1["Date"].max()

'2024-12-01'

# Peak Demand Data's

In [51]:
df1["Date"].max()

'2024-12-01'

In [52]:
df=pd.read_excel("../Datasets/Supply dataset.xlsx")
df.head()

,Parameter,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,...,2025-03,2025-04,2025-05,2025-06,2025-07,2025-08,2025-09,2025-10,2025-11,2025-12
0,Coal - Generation (in MU),70195.44,75339.79,69044.77,70322.24,69569.23,75185.34,81921.11,71886.66,75932.58,...,120750.65,115835.15,111274.42,105966.91,103811.19,102453.72,99520.45,96167.54,96119.81,111373.68
1,Oil & Gas - Generation (in MU),3246.28,3242.43,3796.41,3662.57,3854.07,4372.24,4156.93,4038.93,4263.18,...,1785.82,3195.53,2782.33,2809.12,2545.81,2054.73,2440.19,1454.48,1700.54,1978.63
2,Nuclear - Generation (in MU),3506.10,3457.01,3449.28,3022.21,2834.19,2806.70,2876.22,2868.49,2950.27,...,4719.07,4951.45,5137.08,4498.01,4536.36,4105.67,4045.28,4808.57,3860.28,4221.94
3,Hydro - Generation (in MU),9421.19,12854.80,12509.46,15094.48,17779.11,12299.09,9025.41,6821.86,6339.87,...,8763.28,9618.15,13264.60,16775.50,21673.90,23515.94,22317.41,16437.39,9816.95,8767.19
4,Solar - Generation (in MU),512.31,560.91,515.11,455.52,510.73,600.51,726.49,578.11,651.61,...,16811.38,15811.82,14305.32,12927.48,12100.63,12634.93,13556.18,13063.15,13185.97,14946.83

In [53]:
df = df.set_index("Parameter").T.reset_index()
df = df.rename(columns={"index": "Date"})

In [54]:
df.head()

Parameter,Date,Coal - Generation (in MU),Oil & Gas - Generation (in MU),Nuclear - Generation (in MU),Hydro - Generation (in MU),Solar - Generation (in MU),Wind - Generation (in MU),Small-Hydro - Generation (in MU),Bio Power - Generation (in MU),Total,Growth Rate (in %)
0,2015-04,70195.44,3246.28,3506.10,9421.19,512.31,1832.30,519.15,1688.88,90921.65,NaN
1,2015-05,75339.79,3242.43,3457.01,12854.80,560.91,2673.76,685.93,1222.24,100036.87,NaN
2,2015-06,69044.77,3796.41,3449.28,12509.46,515.11,3946.56,775.37,853.03,94889.99,NaN
3,2015-07,70322.24,3662.57,3022.21,15094.48,455.52,6591.88,1069.77,742.60,100961.27,NaN
4,2015-08,69569.23,3854.07,2834.19,17779.11,510.73,5113.45,1166.68,726.06,101553.52,NaN

In [55]:
type(df)

pandas.core.frame.DataFrame

In [56]:
supply=pd.read_excel("../Datasets/Supply dataset.xlsx")
supply.head()

,Parameter,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,...,2025-03,2025-04,2025-05,2025-06,2025-07,2025-08,2025-09,2025-10,2025-11,2025-12
0,Coal - Generation (in MU),70195.44,75339.79,69044.77,70322.24,69569.23,75185.34,81921.11,71886.66,75932.58,...,120750.65,115835.15,111274.42,105966.91,103811.19,102453.72,99520.45,96167.54,96119.81,111373.68
1,Oil & Gas - Generation (in MU),3246.28,3242.43,3796.41,3662.57,3854.07,4372.24,4156.93,4038.93,4263.18,...,1785.82,3195.53,2782.33,2809.12,2545.81,2054.73,2440.19,1454.48,1700.54,1978.63
2,Nuclear - Generation (in MU),3506.10,3457.01,3449.28,3022.21,2834.19,2806.70,2876.22,2868.49,2950.27,...,4719.07,4951.45,5137.08,4498.01,4536.36,4105.67,4045.28,4808.57,3860.28,4221.94
3,Hydro - Generation (in MU),9421.19,12854.80,12509.46,15094.48,17779.11,12299.09,9025.41,6821.86,6339.87,...,8763.28,9618.15,13264.60,16775.50,21673.90,23515.94,22317.41,16437.39,9816.95,8767.19
4,Solar - Generation (in MU),512.31,560.91,515.11,455.52,510.73,600.51,726.49,578.11,651.61,...,16811.38,15811.82,14305.32,12927.48,12100.63,12634.93,13556.18,13063.15,13185.97,14946.83

In [57]:
supply = supply.set_index("Parameter")

# Transpose (rows ↔ columns)
supply = supply.T

# Convert index into a column
supply = supply.reset_index()

# Rename the first column
supply = supply.rename(columns={"index": "Date"})

# Remove the name of the columns index (optional but recommended)
supply.columns.name = None

# Convert Date column to datetime
supply["Date"] = pd.to_datetime(supply["Date"], format="%Y-%m")

# Display
supply.head()

,Date,Coal - Generation (in MU),Oil & Gas - Generation (in MU),Nuclear - Generation (in MU),Hydro - Generation (in MU),Solar - Generation (in MU),Wind - Generation (in MU),Small-Hydro - Generation (in MU),Bio Power - Generation (in MU),Total,Growth Rate (in %)
0,2015-04-01,70195.44,3246.28,3506.10,9421.19,512.31,1832.30,519.15,1688.88,90921.65,NaN
1,2015-05-01,75339.79,3242.43,3457.01,12854.80,560.91,2673.76,685.93,1222.24,100036.87,NaN
2,2015-06-01,69044.77,3796.41,3449.28,12509.46,515.11,3946.56,775.37,853.03,94889.99,NaN
3,2015-07-01,70322.24,3662.57,3022.21,15094.48,455.52,6591.88,1069.77,742.60,100961.27,NaN
4,2015-08-01,69569.23,3854.07,2834.19,17779.11,510.73,5113.45,1166.68,726.06,101553.52,NaN

In [58]:
cols=supply.columns
supply=supply.drop(columns=cols[-1])
supply.head()

,Date,Coal - Generation (in MU),Oil & Gas - Generation (in MU),Nuclear - Generation (in MU),Hydro - Generation (in MU),Solar - Generation (in MU),Wind - Generation (in MU),Small-Hydro - Generation (in MU),Bio Power - Generation (in MU),Total
0,2015-04-01,70195.44,3246.28,3506.10,9421.19,512.31,1832.30,519.15,1688.88,90921.65
1,2015-05-01,75339.79,3242.43,3457.01,12854.80,560.91,2673.76,685.93,1222.24,100036.87
2,2015-06-01,69044.77,3796.41,3449.28,12509.46,515.11,3946.56,775.37,853.03,94889.99
3,2015-07-01,70322.24,3662.57,3022.21,15094.48,455.52,6591.88,1069.77,742.60,100961.27
4,2015-08-01,69569.23,3854.07,2834.19,17779.11,510.73,5113.45,1166.68,726.06,101553.52

In [59]:
supply.to_csv("../Datasets_For_Model_Training/Supply dataset.csv",index=False)

In [60]:
final=pd.read_csv("../Datasets/final_merged_dataset.csv")
final.head()

,Date,Electricity_Requirement,Humidity,Rainfall,Solar_Irradiance,Coal_Generation,Oil_Gas_Generation,Nuclear_Generation,Hydro_Generation,Solar_Generation,Wind_Generation,Small_Hydro_Generation,Bio_Power_Generation,Total_Supply_Generation,Temperature
0,01-04-2015,8953,70.07,130.566857,166.53,70195.44,3246.28,3506.10,9421.19,512.31,1832.30,519.15,1688.88,90921.65,28.57
1,01-05-2015,8535,77.22,160.792286,155.03,75339.79,3242.43,3457.01,12854.80,560.91,2673.76,685.93,1222.24,100036.87,27.95
2,01-06-2015,8498,77.55,98.240286,160.31,69044.77,3796.41,3449.28,12509.46,515.11,3946.56,775.37,853.03,94889.99,27.31
3,01-07-2015,8330,73.18,37.804286,166.41,70322.24,3662.57,3022.21,15094.48,455.52,6591.88,1069.77,742.60,100961.27,27.68
4,01-08-2015,6511,72.58,63.944286,167.12,69569.23,3854.07,2834.19,17779.11,510.73,5113.45,1166.68,726.06,101553.52,27.85

In [61]:
final.shape

(117, 15)

## Removed the Peak Demand and need to add the Electricity Requirement

## Let us convert back to the CSV File

In [62]:
final.to_csv("../Datasets/final_merged_dataset.csv",index=False)

In [63]:
er=pd.read_csv("../Datasets/Electricity Requirement.csv")
er.head()

,Parameter,STATE,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,...,2025-08,2025-09,2025-10,2025-11,2025-12,2026-01,2026-02,2026-03,2026-04,2026-05
0,Electricity Requirement(in MU),Tamil Nadu,8361.0,8381.0,8302.0,8953.0,8535.0,8498.0,8330.0,6511.0,...,11271.0,10972.0,10087.0,10076.0,10150.0,10067.0,10125.0,12233.0,12922.0,12400.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Keeping only one row

In [64]:
er=er.iloc[[0]]
er.head()

,Parameter,STATE,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,...,2025-08,2025-09,2025-10,2025-11,2025-12,2026-01,2026-02,2026-03,2026-04,2026-05
0,Electricity Requirement(in MU),Tamil Nadu,8361.0,8381.0,8302.0,8953.0,8535.0,8498.0,8330.0,6511.0,...,11271.0,10972.0,10087.0,10076.0,10150.0,10067.0,10125.0,12233.0,12922.0,12400.0

## Removing the unncessary columns

In [65]:
er=er.drop(columns=["Parameter","STATE"])

In [66]:
er.head()

,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,...,2025-08,2025-09,2025-10,2025-11,2025-12,2026-01,2026-02,2026-03,2026-04,2026-05
0,8361.0,8381.0,8302.0,8953.0,8535.0,8498.0,8330.0,6511.0,7181.0,8151.0,...,11271.0,10972.0,10087.0,10076.0,10150.0,10067.0,10125.0,12233.0,12922.0,12400.0

## Transpose the rows into columns

In [67]:
er=er.T.reset_index()
er.head()

     index       0
0  2015-04  8361.0
1  2015-05  8381.0
2  2015-06  8302.0
3  2015-07  8953.0
4  2015-08  8535.0

In [68]:
er.columns=["Date","Electricity_Requirement"]

In [69]:
er["Date"]=pd.to_datetime(df["Date"],format="%Y-%m")

In [70]:
er.head()

        Date  Electricity_Requirement
0 2015-04-01                   8361.0
1 2015-05-01                   8381.0
2 2015-06-01                   8302.0
3 2015-07-01                   8953.0
4 2015-08-01                   8535.0

## Merging into final merged datasets

In [71]:
existing=pd.read_csv("../Datasets/final_merged_dataset.csv")
existing.head()

,Date,Electricity_Requirement,Humidity,Rainfall,Solar_Irradiance,Coal_Generation,Oil_Gas_Generation,Nuclear_Generation,Hydro_Generation,Solar_Generation,Wind_Generation,Small_Hydro_Generation,Bio_Power_Generation,Total_Supply_Generation,Temperature
0,01-04-2015,8953,70.07,130.566857,166.53,70195.44,3246.28,3506.10,9421.19,512.31,1832.30,519.15,1688.88,90921.65,28.57
1,01-05-2015,8535,77.22,160.792286,155.03,75339.79,3242.43,3457.01,12854.80,560.91,2673.76,685.93,1222.24,100036.87,27.95
2,01-06-2015,8498,77.55,98.240286,160.31,69044.77,3796.41,3449.28,12509.46,515.11,3946.56,775.37,853.03,94889.99,27.31
3,01-07-2015,8330,73.18,37.804286,166.41,70322.24,3662.57,3022.21,15094.48,455.52,6591.88,1069.77,742.60,100961.27,27.68
4,01-08-2015,6511,72.58,63.944286,167.12,69569.23,3854.07,2834.19,17779.11,510.73,5113.45,1166.68,726.06,101553.52,27.85

In [72]:
existing["Date"]=pd.to_datetime(existing["Date"])
existing["Date"].dtype

dtype('<M8[ns]')

In [73]:
er["Date"].dtype

dtype('<M8[ns]')

## yes now converted to proper format so we can continue

In [74]:
merged_df=pd.merge(existing,er,on="Date",how="inner")

In [75]:
merged_df.head()

,Date,Electricity_Requirement_x,Humidity,Rainfall,Solar_Irradiance,Coal_Generation,Oil_Gas_Generation,Nuclear_Generation,Hydro_Generation,Solar_Generation,Wind_Generation,Small_Hydro_Generation,Bio_Power_Generation,Total_Supply_Generation,Temperature,Electricity_Requirement_y
0,2016-01-01,9847,78.24,2.164286,162.75,78841.02,3946.32,3056.56,6159.08,535.11,1056.32,449.36,2325.40,96369.17,23.84,8151.0
1,2017-01-01,9539,66.75,41.844286,151.66,82448.20,3563.09,3042.82,6450.46,1183.56,2308.46,301.53,1991.17,101289.29,25.03,8286.6
2,2018-01-01,10127,72.98,7.354857,162.38,86649.50,3854.21,4050.81,6619.51,2541.67,2007.52,383.42,2450.59,108557.23,24.18,8620.9
3,2019-01-01,10308,67.84,0.786286,136.78,86342.55,3971.55,3120.11,7366.66,3386.93,2851.89,428.58,2617.92,110086.19,24.33,8681.0
4,2020-01-01,7287,76.99,9.249714,158.50,87368.85,3392.71,3437.39,8665.07,4612.73,3319.96,562.16,2204.11,113562.98,24.82,8544.0

In [76]:
# Move Electricity_Requirement to the 2nd column
cols = list(merged_df.columns)

cols.remove("Electricity_Requirement")
cols.insert(1, "Electricity_Requirement")

merged_df = merged_df[cols]

ValueError: list.remove(x): x not in list

In [ ]:
merged_df["Electricity_Requirement"]=merged_df["Electricity_Requirement"].astype(int)
merged_df.head()

,Date,Electricity_Requirement,Humidity,Rainfall,Solar_Irradiance,Coal - Generation (in MU),Oil & Gas - Generation (in MU),Nuclear - Generation (in MU),Hydro - Generation (in MU),Solar - Generation (in MU),Wind - Generation (in MU),Small-Hydro - Generation (in MU),Bio Power - Generation (in MU),Total,Temperature
0,2015-04-01,8953,70.07,130.566857,166.53,70195.44,3246.28,3506.10,9421.19,512.31,1832.30,519.15,1688.88,90921.65,28.57
1,2015-05-01,8535,77.22,160.792286,155.03,75339.79,3242.43,3457.01,12854.80,560.91,2673.76,685.93,1222.24,100036.87,27.95
2,2015-06-01,8498,77.55,98.240286,160.31,69044.77,3796.41,3449.28,12509.46,515.11,3946.56,775.37,853.03,94889.99,27.31
3,2015-07-01,8330,73.18,37.804286,166.41,70322.24,3662.57,3022.21,15094.48,455.52,6591.88,1069.77,742.60,100961.27,27.68
4,2015-08-01,6511,72.58,63.944286,167.12,69569.23,3854.07,2834.19,17779.11,510.73,5113.45,1166.68,726.06,101553.52,27.85

In [ ]:
merged_df.rename(columns={
    "Coal - Generation (in MU)": "Coal_Generation",
    "Oil & Gas - Generation (in MU)": "Oil_Gas_Generation",
    "Nuclear - Generation (in MU)": "Nuclear_Generation",
    "Hydro - Generation (in MU)": "Hydro_Generation",
    "Solar - Generation (in MU)": "Solar_Generation",
    "Wind - Generation (in MU)": "Wind_Generation",
    "Small-Hydro - Generation (in MU)": "Small_Hydro_Generation",
    "Bio Power - Generation (in MU)": "Bio_Power_Generation",
    "Solar_Irradiance": "Solar_Irradiance",
    "Electricity_Requirement": "Electricity_Requirement",
    "Temperature": "Temperature",
    "Humidity": "Humidity",
    "Rainfall": "Rainfall",
    "Total": "Total_Supply_Generation"
}, inplace=True)

In [ ]:
merged_df.head()

,Date,Electricity_Requirement,Humidity,Rainfall,Solar_Irradiance,Coal_Generation,Oil_Gas_Generation,Nuclear_Generation,Hydro_Generation,Solar_Generation,Wind_Generation,Small_Hydro_Generation,Bio_Power_Generation,Total_Supply_Generation,Temperature
0,2015-04-01,8953,70.07,130.566857,166.53,70195.44,3246.28,3506.10,9421.19,512.31,1832.30,519.15,1688.88,90921.65,28.57
1,2015-05-01,8535,77.22,160.792286,155.03,75339.79,3242.43,3457.01,12854.80,560.91,2673.76,685.93,1222.24,100036.87,27.95
2,2015-06-01,8498,77.55,98.240286,160.31,69044.77,3796.41,3449.28,12509.46,515.11,3946.56,775.37,853.03,94889.99,27.31
3,2015-07-01,8330,73.18,37.804286,166.41,70322.24,3662.57,3022.21,15094.48,455.52,6591.88,1069.77,742.60,100961.27,27.68
4,2015-08-01,6511,72.58,63.944286,167.12,69569.23,3854.07,2834.19,17779.11,510.73,5113.45,1166.68,726.06,101553.52,27.85

In [ ]:
merged_df.shape

(117, 15)

In [ ]:
print(merged_df["Date"].min())
print(merged_df["Date"].max())
print(len(merged_df))

2015-04-01 00:00:00
2024-12-01 00:00:00
117

In [ ]:
merged_df.to_csv("../Datasets/final_merged_dataset.csv",index=False)

In [4]:
import pandas as pd

# Read Excel
df = pd.read_csv("../Datasets_For_Model_Training/Electricity Requirement.csv")

# Convert wide format to long format
long_df = df.melt(
    id_vars=["Parameter", "STATE"],
    var_name="Date",
    value_name="Electricity_Requirement"
)

# Keep only required columns
long_df = long_df[["Date", "Electricity_Requirement"]]

# Convert Date column
long_df["Date"] = pd.to_datetime(long_df["Date"])

# Sort by date
long_df = long_df.sort_values("Date").reset_index(drop=True)

# Save
long_df.to_csv(
    "Electricity_Requirement.csv",
    index=False
)

long_df.head(30)

         Date  Electricity_Requirement
0  2015-04-01                   8361.0
1  2015-04-01                      NaN
2  2015-04-01                      NaN
3  2015-04-01                      NaN
4  2015-04-01                      NaN
5  2015-05-01                   8381.0
6  2015-05-01                      NaN
7  2015-05-01                      NaN
8  2015-05-01                      NaN
9  2015-05-01                      NaN
10 2015-06-01                      NaN
11 2015-06-01                      NaN
12 2015-06-01                   8302.0
13 2015-06-01                      NaN
14 2015-06-01                      NaN
15 2015-07-01                   8953.0
16 2015-07-01                      NaN
17 2015-07-01                      NaN
18 2015-07-01                      NaN
19 2015-07-01                      NaN
20 2015-08-01                      NaN
21 2015-08-01                      NaN
22 2015-08-01                   8535.0
23 2015-08-01                      NaN
24 2015-08-01                      NaN
25 2015-09-01                   8498.0
26 2015-09-01                      NaN
27 2015-09-01                      NaN
28 2015-09-01                      NaN
29 2015-09-01                      NaN

In [7]:
long_df.dropna(inplace=True)

In [9]:
long_df.to_csv("../Datasets_For_Model_Training/Electricity Requirement.csv",index=False)