# importing necessary libraries to do the pre-processing

In [1]:
import numpy as np
import pandas as pd

# Loading the Dataset from the folder

In [2]:
df=pd.read_csv("../Datasets/solar_irradiance.csv")
df.head()

         Date  Solar_Irradiance
0  2015-01-01            146.56
1  2015-02-01            162.97
2  2015-03-01            194.53
3  2015-04-01            166.53
4  2015-05-01            155.03

# Keeping only important columns

In [3]:
df=df.iloc[:,2:]
df.head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

# Extracting the columns from the datasets

In [4]:
months=df.columns
months

Index([], dtype='object')

# Doing the average for the 32 districts and making it for single year and round that value to 2 decimbal places

In [5]:
month_avg=df.groupby("Year")[months[1:]].mean().reset_index().round(2)
month_avg

KeyError: 'Year'

# converting the rows into cols for better readability and model training too

In [ ]:
final=month_avg.melt(
    id_vars="Year",
    var_name="Months",
    value_name="Solar_Irradiance"
)

In [ ]:
final

     Year    Months  Solar_Irradiance
0    2015   January            146.56
1    2016   January            162.75
2    2017   January            151.66
3    2018   January            162.38
4    2019   January            136.78
..    ...       ...               ...
115  2020  December            128.50
116  2021  December            150.62
117  2022  December            123.69
118  2023  December            126.44
119  2024  December             98.66

[120 rows x 3 columns]

# Doing the Feature Engineering and making the Date column from the Year and Month

In [ ]:
final["Date"]=pd.to_datetime(
final["Year"].astype(str)+"-"+final["Months"],
format="%Y-%B"
)

In [ ]:
final=final[["Date","Solar_Irradiance"]]
final=final.sort_values("Date")
final.head()

         Date  Solar_Irradiance
0  2015-01-01            146.56
10 2015-02-01            162.97
20 2015-03-01            194.53
30 2015-04-01            166.53
40 2015-05-01            155.03

In [ ]:
final.to_csv("../Datasets/solar_irradiance.csv",index=False)

# Checking the Strcuture of the dataset

In [ ]:
df1=pd.read_csv("../Datasets/solar_irradiance.csv")

         Date  Solar_Irradiance
0  2015-01-01            146.56
1  2015-02-01            162.97
2  2015-03-01            194.53
3  2015-04-01            166.53
4  2015-05-01            155.03

In [ ]:
import pandas as pd

df = pd.read_csv("../Datasets/solar_irradiance_from_2025.csv", nrows=5)
df.head()

,_id,SlNo,Station,Agency,State LGD Code,State,District LGD Code,District,Tehsil,Block,...,River,Basin,Tributary,Subtributary,SubSubtributary,Local River,Latitude,Longitude,Data Acquisition Time,Solar Radiation (Watt/m2)
0,1,1,Aralvaimozhi,Tamil Nadu SW GW,33,Tamil Nadu,575,Kanyakumari,Thovalai,-,...,-,-,-,-,-,-,8.247222,77.545,15-12-2021 17:00,60
1,2,2,Aralvaimozhi,Tamil Nadu SW GW,33,Tamil Nadu,575,Kanyakumari,Thovalai,-,...,-,-,-,-,-,-,8.247222,77.545,15-12-2021 18:00,0
2,3,3,Aralvaimozhi,Tamil Nadu SW GW,33,Tamil Nadu,575,Kanyakumari,Thovalai,-,...,-,-,-,-,-,-,8.247222,77.545,15-12-2021 19:00,0
3,4,4,Aralvaimozhi,Tamil Nadu SW GW,33,Tamil Nadu,575,Kanyakumari,Thovalai,-,...,-,-,-,-,-,-,8.247222,77.545,16-12-2021 10:00,343
4,5,5,Aralvaimozhi,Tamil Nadu SW GW,33,Tamil Nadu,575,Kanyakumari,Thovalai,-,...,-,-,-,-,-,-,8.247222,77.545,16-12-2021 11:00,414

In [ ]:
import pandas as pd

input_file = "../Datasets/solar_irradiance_from_2025.csv"
output_file = "Solar_Radiation_2025_Onwards.csv"

chunksize = 100000

first_chunk = True

for chunk in pd.read_csv(input_file, chunksize=chunksize):

    # Convert to datetime
    chunk["Data Acquisition Time"] = pd.to_datetime(
        chunk["Data Acquisition Time"],
        format="%d-%m-%Y %H:%M",
        errors="coerce"
    )

    # Filter from 01-Jan-2025 onwards
    filtered = chunk[
        chunk["Data Acquisition Time"] >= "2025-01-01"
    ]

    # Save incrementally
    filtered.to_csv(
        output_file,
        mode="w" if first_chunk else "a",
        index=False,
        header=first_chunk
    )

    first_chunk = False

print("Filtering completed successfully!")

Filtering completed successfully!

In [ ]:
df=pd.read_csv("../Datasets/Solar_Radiation_2025_Onwards.csv")
df.head()

,_id,SlNo,Station,Agency,State LGD Code,State,District LGD Code,District,Tehsil,Block,...,River,Basin,Tributary,Subtributary,SubSubtributary,Local River,Latitude,Longitude,Data Acquisition Time,Solar Radiation (Watt/m2)
0,23789,23789,Aralvaimozhi,Tamil Nadu SW GW,33,Tamil Nadu,575,Kanyakumari,Thovalai,-,...,-,-,-,-,-,-,8.247222,77.545,2025-01-01 00:00:00,0
1,23790,23790,Aralvaimozhi,Tamil Nadu SW GW,33,Tamil Nadu,575,Kanyakumari,Thovalai,-,...,-,-,-,-,-,-,8.247222,77.545,2025-01-01 00:30:00,0
2,23791,23791,Aralvaimozhi,Tamil Nadu SW GW,33,Tamil Nadu,575,Kanyakumari,Thovalai,-,...,-,-,-,-,-,-,8.247222,77.545,2025-01-01 01:00:00,0
3,23792,23792,Aralvaimozhi,Tamil Nadu SW GW,33,Tamil Nadu,575,Kanyakumari,Thovalai,-,...,-,-,-,-,-,-,8.247222,77.545,2025-01-01 01:30:00,0
4,23793,23793,Aralvaimozhi,Tamil Nadu SW GW,33,Tamil Nadu,575,Kanyakumari,Thovalai,-,...,-,-,-,-,-,-,8.247222,77.545,2025-01-01 02:00:00,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 379481 entries, 0 to 379480
Data columns (total 21 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   _id                        379481 non-null  int64
 1   SlNo                       379481 non-null  int64
 2   Station                    379481 non-null  object
 3   Agency                     379481 non-null  object
 4   State LGD Code             379481 non-null  int64
 5   State                      379481 non-null  object
 6   District LGD Code          379481 non-null  int64
 7   District                   379481 non-null  object
 8   Tehsil                     379481 non-null  object
 9   Block                      379481 non-null  object
 10  Village                    379481 non-null  object
 11  River                      379481 non-null  object
 12  Basin                      379481 non-null  object
 13  Tributary                  379481 non-null  object
 14  Subtributary               379481 non-null  object
 15  SubSubtributary            379481 non-null  object
 16  Local River                379481 non-null  object
 17  Latitude                   379481 non-null  float64
 18  Longitude                  379481 non-null  float64
 19  Data Acquisition Time      379481 non-null  object
 20  Solar Radiation (Watt/m2)  379481 non-null  int64
dtypes: float64(2), int64(5), object(14)
memory usage: 60.8+ MB

In [ ]:
df["Data Acquisition Time"] = pd.to_datetime(
    df["Data Acquisition Time"]
)

In [ ]:
df["Date"] = df["Data Acquisition Time"].dt.date

In [ ]:
daily_district = (
    df.groupby(
        ["District", "Date"]
    )["Solar Radiation (Watt/m2)"]
    .mean()
    .reset_index()
)

In [ ]:
daily_district.head()

       District        Date  Solar Radiation (Watt/m2)
0  Chengalpattu  2025-01-01                  49.103448
1  Chengalpattu  2025-01-02                 112.931818
2  Chengalpattu  2025-01-03                 107.076923
3  Chengalpattu  2025-01-04                 129.071429
4  Chengalpattu  2025-01-05                  82.000000

In [ ]:
tn_daily = (
    daily_district.groupby("Date")["Solar Radiation (Watt/m2)"]
    .mean()
    .reset_index()
)

In [ ]:
tn_daily.head()

         Date  Solar Radiation (Watt/m2)
0  2025-01-01                 274.000879
1  2025-01-02                 289.187167
2  2025-01-03                 268.028566
3  2025-01-04                 270.830686
4  2025-01-05                 269.622065

In [ ]:
tn_daily["Date"] = pd.to_datetime(tn_daily["Date"])

In [ ]:
tn_daily["Year"] = tn_daily["Date"].dt.year
tn_daily["Month"] = tn_daily["Date"].dt.month

In [ ]:
monthly_avg = (
    tn_daily.groupby(["Year", "Month"])["Solar Radiation (Watt/m2)"]
    .mean()
    .reset_index()
)

In [ ]:
monthly_avg["Date"] = pd.to_datetime(
    monthly_avg[["Year", "Month"]].assign(DAY=1)
)

In [ ]:
monthly_avg = monthly_avg[
    ["Date", "Solar Radiation (Watt/m2)"]
]

In [ ]:
monthly_avg.rename(
    columns={
        "Solar Radiation (Watt/m2)": "Solar_Irradiance"
    },
    inplace=True
)

In [ ]:
monthly_avg.head(15)

         Date  Solar_Irradiance
0  2025-01-01        268.909644
1  2025-02-01        252.323688
2  2025-03-01        289.310913
3  2025-04-01        303.305385
4  2025-05-01        224.889697
5  2025-06-01        229.882395
6  2025-07-01        248.838219
7  2025-08-01        230.109299
8  2025-09-01        222.625642
9  2025-10-01        206.786604
10 2025-11-01        197.768678
11 2025-12-01        207.785029

In [ ]:
monthly_avg.to_csv(
    "../Datasets/TamilNadu_Solar_Irradiance_2025_Monthly.csv",
    index=False
)

In [6]:
import pandas as pd

In [7]:
df=pd.read_csv("../Datasets_For_Model_Training/TamilNadu_Solar_Irradiance_2025_Monthly.csv")
df.head()

         Date  Solar_Irradiance
0  2025-01-01        268.909644
1  2025-02-01        252.323688
2  2025-03-01        289.310913
3  2025-04-01        303.305385
4  2025-05-01        224.889697

In [9]:
df1=pd.read_csv("../Datasets_For_Model_Training/solar_irradiance.csv")
df1.tail()

           Date  Solar_Irradiance
115  2024-08-01            147.25
116  2024-09-01            156.84
117  2024-10-01            120.78
118  2024-11-01            101.47
119  2024-12-01             98.66

In [12]:
df1["Date"]=pd.to_datetime(df["Date"])

In [14]:
df["Date"]=pd.to_datetime(df["Date"])

In [17]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              12 non-null     datetime64[ns]
 1   Solar_Irradiance  120 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 2.0 KB

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              12 non-null     datetime64[ns]
 1   Solar_Irradiance  12 non-null     float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 324.0 bytes

In [25]:
merged_df=pd.merge(df1,df,on="Date",how="inner")

In [21]:
merged_df.to_csv("../Datasets_For_Model_Training/solar_irradiance.csv",index=False)

In [27]:
merged_df.head()

        Date  Solar_Irradiance_x  Solar_Irradiance_y
0 2025-01-01              146.56          268.909644
1 2025-02-01              162.97          252.323688
2 2025-03-01              194.53          289.310913
3 2025-04-01              166.53          303.305385
4 2025-05-01              155.03          224.889697

In [28]:
final_df=pd.concat([df1,df],ignore_index=True)

In [31]:
final_df["Date"] = pd.to_datetime(final_df["Date"])

In [32]:
final_df = final_df.sort_values("Date").reset_index(drop=True)

In [33]:
final_df.head()

        Date  Solar_Irradiance
0 2025-01-01        146.560000
1 2025-01-01        268.909644
2 2025-02-01        162.970000
3 2025-02-01        252.323688
4 2025-03-01        194.530000