In [4]:
import numpy as np
import pandas as pd

# We are Pre-processing the Humidity Datasets

In [5]:
df = pd.read_csv(
    "../Datasets/Humidity Datasets.csv",
    skiprows=21
)

df.head()

   2016-09-01   70.5
0  2016-10-01  70.23
1  2016-11-01  71.24
2  2016-12-01  70.23
3  2017-01-01  66.75
4  2017-02-01  59.91

In [6]:
months=df.columns

In [7]:
monthly_avg = df.groupby("YEAR")[months[3:]].mean().reset_index()

KeyError: 'YEAR'

In [ ]:
monthly_avg.drop("ANN",axis=1,inplace=True)

In [ ]:
humidity = monthly_avg.melt(
    id_vars="YEAR",
    var_name="Month",
    value_name="Humidity"
)

In [ ]:
humidity

     YEAR Month   Humidity
0    2015   JAN  24.162571
1    2016   JAN  23.840571
2    2017   JAN  25.032000
3    2018   JAN  24.175143
4    2019   JAN  24.326000
..    ...   ...        ...
127  2021   DEC  23.939429
128  2022   DEC  24.342571
129  2023   DEC  25.031429
130  2024   DEC  25.078286
131  2025   DEC  23.562000

[132 rows x 3 columns]

In [ ]:
humidity["Date"] = pd.to_datetime(
    humidity["YEAR"].astype(str) + "-" + humidity["Month"],
    format="%Y-%b"
)

In [ ]:
humidity

     YEAR Month   Humidity       Date
0    2015   JAN  24.162571 2015-01-01
1    2016   JAN  23.840571 2016-01-01
2    2017   JAN  25.032000 2017-01-01
3    2018   JAN  24.175143 2018-01-01
4    2019   JAN  24.326000 2019-01-01
..    ...   ...        ...        ...
127  2021   DEC  23.939429 2021-12-01
128  2022   DEC  24.342571 2022-12-01
129  2023   DEC  25.031429 2023-12-01
130  2024   DEC  25.078286 2024-12-01
131  2025   DEC  23.562000 2025-12-01

[132 rows x 4 columns]

In [ ]:
humidity = humidity[["Date", "Humidity"]]
humidity

          Date   Humidity
0   2015-01-01  24.162571
1   2016-01-01  23.840571
2   2017-01-01  25.032000
3   2018-01-01  24.175143
4   2019-01-01  24.326000
..         ...        ...
127 2021-12-01  23.939429
128 2022-12-01  24.342571
129 2023-12-01  25.031429
130 2024-12-01  25.078286
131 2025-12-01  23.562000

[132 rows x 2 columns]

In [ ]:
humidity = humidity.sort_values("Date").reset_index(drop=True)

In [ ]:
humidity

          Date   Humidity
0   2015-01-01  24.162571
1   2015-02-01  25.834571
2   2015-03-01  28.345429
3   2015-04-01  28.566000
4   2015-05-01  27.947143
..         ...        ...
127 2025-08-01  27.277714
128 2025-09-01  27.485714
129 2025-10-01  26.676286
130 2025-11-01  25.315714
131 2025-12-01  23.562000

[132 rows x 2 columns]

In [ ]:
humidity["Humidity"] = humidity["Humidity"].round(2)
humidity

          Date  Humidity
0   2015-01-01     24.16
1   2015-02-01     25.83
2   2015-03-01     28.35
3   2015-04-01     28.57
4   2015-05-01     27.95
..         ...       ...
127 2025-08-01     27.28
128 2025-09-01     27.49
129 2025-10-01     26.68
130 2025-11-01     25.32
131 2025-12-01     23.56

[132 rows x 2 columns]

In [ ]:
humidity.to_csv("../Datasets/Humidity Datasets.csv",index=False)

# 👆👆 we are converted to the structured datasets of humidity

# 👇 Going to process the Rainfall Datasets

In [ ]:
df=pd.read_csv("../Datasets/Rainfall datasets.csv")
df.head()

,PARAMETER,YEAR,LAT,LON,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
0,PRECTOTCORR_SUM,2015,10.0,76.875,4.12,1.74,37.53,133.56,195.74,278.78,143.46,133.26,213.92,220.06,234.50,84.09,1680.76
1,PRECTOTCORR_SUM,2015,10.0,77.500,3.60,1.47,18.66,130.82,175.49,107.38,43.67,66.87,146.70,114.95,217.66,89.03,1116.30
2,PRECTOTCORR_SUM,2015,10.0,78.125,3.75,4.23,15.72,127.99,177.84,71.34,39.25,58.20,149.16,94.70,223.13,99.02,1064.33
3,PRECTOTCORR_SUM,2015,10.0,78.750,4.05,10.89,10.23,120.30,177.62,54.36,23.51,61.75,133.07,142.02,302.05,148.65,1188.50
4,PRECTOTCORR_SUM,2015,10.0,79.375,3.83,16.67,13.54,111.67,180.64,50.23,19.96,65.90,101.75,193.48,445.71,228.24,1431.62

In [ ]:
df=df.iloc[:,1:]
df.head()

,YEAR,LAT,LON,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
0,2015,10.0,76.875,4.12,1.74,37.53,133.56,195.74,278.78,143.46,133.26,213.92,220.06,234.50,84.09,1680.76
1,2015,10.0,77.500,3.60,1.47,18.66,130.82,175.49,107.38,43.67,66.87,146.70,114.95,217.66,89.03,1116.30
2,2015,10.0,78.125,3.75,4.23,15.72,127.99,177.84,71.34,39.25,58.20,149.16,94.70,223.13,99.02,1064.33
3,2015,10.0,78.750,4.05,10.89,10.23,120.30,177.62,54.36,23.51,61.75,133.07,142.02,302.05,148.65,1188.50
4,2015,10.0,79.375,3.83,16.67,13.54,111.67,180.64,50.23,19.96,65.90,101.75,193.48,445.71,228.24,1431.62

In [ ]:
monthly_avg = df.groupby("YEAR")[
    ["JAN","FEB","MAR","APR","MAY","JUN",
     "JUL","AUG","SEP","OCT","NOV","DEC"]
].mean().reset_index()

In [ ]:
monthly_avg

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
0,2015,24.162571,25.834571,28.345429,28.566000,27.947143,27.313714,27.675714,27.848857,27.500571,26.596000,25.044857,24.365714
1,2016,23.840571,26.387143,29.358857,31.114571,29.449429,27.637143,27.292857,27.546857,27.556571,27.544857,26.064286,25.356286
2,2017,25.032000,25.775429,27.995143,30.780857,29.278857,27.919143,28.078000,27.062286,26.388571,26.385714,25.216286,24.113143
3,2018,24.175143,25.563714,28.213143,29.709714,28.369714,27.540571,27.206857,26.963429,27.380571,26.181143,25.265714,24.974000
4,2019,24.326000,27.612286,29.550571,30.710857,30.642571,29.005429,28.032000,26.998857,26.635143,25.794000,25.641143,24.482000
5,2020,24.824857,26.523143,29.107714,30.121714,30.107429,28.143714,26.837429,27.017714,26.342857,26.299714,25.508857,23.891714
6,2021,23.958857,24.203429,27.248571,29.098571,28.232000,27.604000,27.022000,26.954286,26.732000,26.070286,24.866571,23.939429
7,2022,24.487714,25.499143,28.082000,28.670000,28.419714,27.266286,26.846857,26.300286,26.524857,26.023714,24.601714,24.342571
8,2023,23.663429,25.330857,28.079714,29.703143,28.582571,28.528571,27.758286,28.467714,27.066571,26.975714,25.644571,25.031429
9,2024,24.620571,26.741714,29.159429,31.318286,29.496000,27.463429,27.326286,27.162000,27.793429,26.529714,25.436571,25.078286
10,2025,23.859429,25.732286,28.228857,28.970286,28.830857,28.120286,28.018571,27.277714,27.485714,26.676286,25.315714,23.562000

In [ ]:
rainfall = monthly_avg.melt(
    id_vars="YEAR",
    var_name="Month",
    value_name="Rainfall"
)
rainfall

     YEAR Month    Rainfall
0    2015   JAN    3.566000
1    2016   JAN    2.164286
2    2017   JAN   41.844286
3    2018   JAN    7.354857
4    2019   JAN    0.786286
..    ...   ...         ...
127  2021   DEC   63.789429
128  2022   DEC  139.088857
129  2023   DEC  175.832857
130  2024   DEC  160.731143
131  2025   DEC   40.279714

[132 rows x 3 columns]

In [ ]:
rainfall["Date"] = pd.to_datetime(
    rainfall["YEAR"].astype(str) + "-" + rainfall["Month"],
    format="%Y-%b"
)
rainfall

     YEAR Month    Rainfall       Date
0    2015   JAN    3.566000 2015-01-01
1    2016   JAN    2.164286 2016-01-01
2    2017   JAN   41.844286 2017-01-01
3    2018   JAN    7.354857 2018-01-01
4    2019   JAN    0.786286 2019-01-01
..    ...   ...         ...        ...
127  2021   DEC   63.789429 2021-12-01
128  2022   DEC  139.088857 2022-12-01
129  2023   DEC  175.832857 2023-12-01
130  2024   DEC  160.731143 2024-12-01
131  2025   DEC   40.279714 2025-12-01

[132 rows x 4 columns]

In [ ]:
rainfall = rainfall[["Date", "Rainfall"]]
rainfall

          Date    Rainfall
0   2015-01-01    3.566000
1   2016-01-01    2.164286
2   2017-01-01   41.844286
3   2018-01-01    7.354857
4   2019-01-01    0.786286
..         ...         ...
127 2021-12-01   63.789429
128 2022-12-01  139.088857
129 2023-12-01  175.832857
130 2024-12-01  160.731143
131 2025-12-01   40.279714

[132 rows x 2 columns]

In [ ]:
rainfall = rainfall.sort_values("Date").reset_index(drop=True)
rainfall

          Date    Rainfall
0   2015-01-01    3.566000
1   2015-02-01    6.179714
2   2015-03-01   22.411143
3   2015-04-01  130.566857
4   2015-05-01  160.792286
..         ...         ...
127 2025-08-01   82.058571
128 2025-09-01  105.152571
129 2025-10-01  227.279714
130 2025-11-01  206.957714
131 2025-12-01   40.279714

[132 rows x 2 columns]

# 👇Replaced existing rainfall file with structured one

In [ ]:
rainfall.to_csv("../Datasets/Rainfall datasets.csv",index=False)

In [ ]:
df1=pd.read_csv("../Datasets/Rainfall datasets.csv")
df1.head()

NameError: name 'pd' is not defined

# 👇 Pre-processing the Temperature datasets

In [ ]:
df=pd.read_csv("../Datasets/Temperature Dataset.csv",skiprows=21)
df.head()

,PARAMETER,YEAR,LAT,LON,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
0,T2M,2015,10.0,76.875,21.26,23.33,25.32,25.19,24.14,22.90,22.56,22.69,22.75,22.78,22.04,21.75,23.06
1,T2M,2015,10.0,77.500,21.34,22.79,25.84,25.94,25.29,23.99,24.27,24.60,24.54,23.44,22.06,21.23,23.78
2,T2M,2015,10.0,78.125,24.01,25.87,28.91,28.69,28.44,27.98,28.71,29.02,28.42,26.73,24.85,23.82,27.13
3,T2M,2015,10.0,78.750,24.66,26.44,29.30,29.57,28.76,28.80,29.98,30.06,29.28,27.35,25.73,24.81,27.90
4,T2M,2015,10.0,79.375,25.22,26.47,28.59,29.69,29.38,29.55,30.16,29.99,29.39,28.33,26.90,26.27,28.34

In [ ]:
df=df.iloc[:,1:]
df.head()

,YEAR,LAT,LON,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
0,2015,10.0,76.875,21.26,23.33,25.32,25.19,24.14,22.90,22.56,22.69,22.75,22.78,22.04,21.75,23.06
1,2015,10.0,77.500,21.34,22.79,25.84,25.94,25.29,23.99,24.27,24.60,24.54,23.44,22.06,21.23,23.78
2,2015,10.0,78.125,24.01,25.87,28.91,28.69,28.44,27.98,28.71,29.02,28.42,26.73,24.85,23.82,27.13
3,2015,10.0,78.750,24.66,26.44,29.30,29.57,28.76,28.80,29.98,30.06,29.28,27.35,25.73,24.81,27.90
4,2015,10.0,79.375,25.22,26.47,28.59,29.69,29.38,29.55,30.16,29.99,29.39,28.33,26.90,26.27,28.34

In [ ]:
months=df.columns

Index(['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT',
       'NOV', 'DEC', 'ANN'],
      dtype='object')

In [ ]:
monthly_avg=df.groupby("YEAR")[months[3:]].mean().reset_index()
monthly_avg.drop("ANN",axis=1,inplace=True)

In [ ]:
final=monthly_avg.melt(
    id_vars="YEAR",
    var_name="Month",
    value_name="Temperature"
)

In [ ]:
final

     YEAR Month  Temperature
0    2015   JAN    24.162571
1    2016   JAN    23.840571
2    2017   JAN    25.032000
3    2018   JAN    24.175143
4    2019   JAN    24.326000
..    ...   ...          ...
127  2021   DEC    23.939429
128  2022   DEC    24.342571
129  2023   DEC    25.031429
130  2024   DEC    25.078286
131  2025   DEC    23.562000

[132 rows x 3 columns]

In [ ]:
final["Date"] = pd.to_datetime(
    final["YEAR"].astype(str) + "-" + final["Month"],
    format="%Y-%b"
)
final

     YEAR Month  Temperature       Date
0    2015   JAN    24.162571 2015-01-01
1    2016   JAN    23.840571 2016-01-01
2    2017   JAN    25.032000 2017-01-01
3    2018   JAN    24.175143 2018-01-01
4    2019   JAN    24.326000 2019-01-01
..    ...   ...          ...        ...
127  2021   DEC    23.939429 2021-12-01
128  2022   DEC    24.342571 2022-12-01
129  2023   DEC    25.031429 2023-12-01
130  2024   DEC    25.078286 2024-12-01
131  2025   DEC    23.562000 2025-12-01

[132 rows x 4 columns]

In [ ]:
final=final[["Date","Temperature"]]
final["Temperature"]=final["Temperature"].round(2)
final

C:\Users\TAMILARASU\AppData\Local\Temp\ipykernel_15324\1441256900.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final["Temperature"]=final["Temperature"].round(2)

          Date  Temperature
0   2015-01-01        24.16
1   2015-02-01        25.83
2   2015-03-01        28.35
3   2015-04-01        28.57
4   2015-05-01        27.95
..         ...          ...
127 2025-08-01        27.28
128 2025-09-01        27.49
129 2025-10-01        26.68
130 2025-11-01        25.32
131 2025-12-01        23.56

[132 rows x 2 columns]

In [ ]:
final.to_csv("../Datasets/Temperature Dataset.csv",index=False)