In [33]:
import pandas as pd
import numpy as np
import joblib

In [34]:
df = pd.read_csv("../Datasets_For_Model_Training/Final_Merged_Dataset.csv")
df.head()

,Date,Electricity_Requirement,Humidity,Rainfall,Solar_Irradiance,Coal,Oil & Gas,Nuclear,Hydro,Solar,Wind,Small-Hydro,Bio Power,Total,Temperature
0,01-04-2015,8361.0,70.07,130.566857,166.53,70195.44,3246.28,3506.10,9421.19,512.31,1832.30,519.15,1688.88,90921.65,28.57
1,01-05-2015,8381.0,77.22,160.792286,155.03,75339.79,3242.43,3457.01,12854.80,560.91,2673.76,685.93,1222.24,100036.87,27.95
2,01-06-2015,8302.0,77.55,98.240286,160.31,69044.77,3796.41,3449.28,12509.46,515.11,3946.56,775.37,853.03,94889.99,27.31
3,01-07-2015,8953.0,73.18,37.804286,166.41,70322.24,3662.57,3022.21,15094.48,455.52,6591.88,1069.77,742.60,100961.27,27.68
4,01-08-2015,8535.0,72.58,63.944286,167.12,69569.23,3854.07,2834.19,17779.11,510.73,5113.45,1166.68,726.06,101553.52,27.85

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     129 non-null    object
 1   Electricity_Requirement  129 non-null    float64
 2   Humidity                 129 non-null    float64
 3   Rainfall                 129 non-null    float64
 4   Solar_Irradiance         129 non-null    float64
 5   Coal                     129 non-null    float64
 6   Oil & Gas                129 non-null    float64
 7   Nuclear                  129 non-null    float64
 8   Hydro                    129 non-null    float64
 9   Solar                    129 non-null    float64
 10  Wind                     129 non-null    float64
 11  Small-Hydro              129 non-null    float64
 12  Bio Power                129 non-null    float64
 13  Total                    129 non-null    float64
 14  Temperature              129 non-null    float64
dtypes: float64(14), object(1)
memory usage: 15.8+ KB

In [36]:
df["Date"] = pd.to_datetime(df["Date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     129 non-null    datetime64[ns]
 1   Electricity_Requirement  129 non-null    float64
 2   Humidity                 129 non-null    float64
 3   Rainfall                 129 non-null    float64
 4   Solar_Irradiance         129 non-null    float64
 5   Coal                     129 non-null    float64
 6   Oil & Gas                129 non-null    float64
 7   Nuclear                  129 non-null    float64
 8   Hydro                    129 non-null    float64
 9   Solar                    129 non-null    float64
 10  Wind                     129 non-null    float64
 11  Small-Hydro              129 non-null    float64
 12  Bio Power                129 non-null    float64
 13  Total                    129 non-null    float64
 14  Temperature              129 non-null    float64
dtypes: datetime64[ns](1), float64(14)
memory usage: 15.8 KB

In [37]:
# extracting year and month
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month

In [38]:
df.dropna(inplace=True)

In [39]:
df.head()

,Date,Electricity_Requirement,Humidity,Rainfall,Solar_Irradiance,Coal,Oil & Gas,Nuclear,Hydro,Solar,Wind,Small-Hydro,Bio Power,Total,Temperature,Year,Month
0,2015-01-04,8361.0,70.07,130.566857,166.53,70195.44,3246.28,3506.10,9421.19,512.31,1832.30,519.15,1688.88,90921.65,28.57,2015.0,1.0
1,2015-01-05,8381.0,77.22,160.792286,155.03,75339.79,3242.43,3457.01,12854.80,560.91,2673.76,685.93,1222.24,100036.87,27.95,2015.0,1.0
2,2015-01-06,8302.0,77.55,98.240286,160.31,69044.77,3796.41,3449.28,12509.46,515.11,3946.56,775.37,853.03,94889.99,27.31,2015.0,1.0
3,2015-01-07,8953.0,73.18,37.804286,166.41,70322.24,3662.57,3022.21,15094.48,455.52,6591.88,1069.77,742.60,100961.27,27.68,2015.0,1.0
4,2015-01-08,8535.0,72.58,63.944286,167.12,69569.23,3854.07,2834.19,17779.11,510.73,5113.45,1166.68,726.06,101553.52,27.85,2015.0,1.0

In [40]:
df.shape

(129, 17)

In [41]:
df.isnull().sum()

Date                       0
Electricity_Requirement    0
Humidity                   0
Rainfall                   0
Solar_Irradiance           0
Coal                       0
Oil & Gas                  0
Nuclear                    0
Hydro                      0
Solar                      0
Wind                       0
Small-Hydro                0
Bio Power                  0
Total                      0
Temperature                0
Year                       0
Month                      0
dtype: int64

In [42]:
# select the target
y = df["Electricity_Requirement"]

# We does require those columns

In [43]:
X = df.drop(
    columns=[
        "Date",
        "Electricity_Requirement",
        "Total"
    ]
)

In [44]:
print(X.columns)

Index(['Humidity', 'Rainfall', 'Solar_Irradiance', 'Coal', 'Oil & Gas',
       'Nuclear', 'Hydro', 'Solar', 'Wind', 'Small-Hydro', 'Bio Power',
       'Temperature', 'Year', 'Month'],
      dtype='object')

In [45]:
print("Features Shape :", X.shape)
print("Target Shape   :", y.shape)

Features Shape : (129, 14)
Target Shape   : (129,)

In [46]:
split = int(len(df) * 0.8)

X_train = X.iloc[:split]
X_test = X.iloc[split:]

y_train = y.iloc[:split]
y_test = y.iloc[split:]

In [47]:
print("X_train :", X_train.shape)
print("X_test  :", X_test.shape)

print("y_train :", y_train.shape)
print("y_test  :", y_test.shape)

X_train : (103, 14)
X_test  : (26, 14)
y_train : (103,)
y_test  : (26,)

# saving the datasets

In [48]:
joblib.dump(X_train, "Demand_X_train.pkl")
joblib.dump(X_test, "Demand_X_test.pkl")

joblib.dump(y_train, "Demand_y_train.pkl")
joblib.dump(y_test, "Demand_y_test.pkl")

['Demand_y_test.pkl']

In [49]:
import os

for i in os.listdir():
    print(i)

00_Preprocessing.ipynb
01Randomforest.ipynb
Demand_X_test.pkl
Demand_X_train.pkl
Demand_y_test.pkl
Demand_y_train.pkl